name: raincheck
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - beautifulsoup4
  - boto3
  - xarray
  - cfgrib
  - pandas
  - pydantic
  - pytz
  - eccodes
  - dash
  - plotly
  - pip
  - pip:
    - redis
